project_id = "kbaazksvkvnafrwtmkcw"

[functions.process-user-query]
timeout = 120

[functions.create-task]
verify_jwt = false
timeout = 600

[functions.openrouter-task-call]
verify_jwt = false
timeout = 600

[functions.ogemath-task-hardcode]
verify_jwt = false
timeout = 600

[functions.student-progress-calculate]
verify_jwt = false
timeout = 600